---
- name: 'Set shared facts'
  set_fact:
    jetty_dist_archive_path='{{ installer.path }}/jetty-distribution-{{ download.jetty.version }}.tar.gz'

- name: 'Create jetty user'
  user: name=jetty

- name: 'Create jetty root'
  file:
    path: '{{ jetty.root }}'
    owner: root
    group: jetty
    state: directory
    mode: 0750

- name: 'Download jetty distribution'
  get_url:
    url: '{{ urls.jetty.url }}'
    dest: '{{ jetty_dist_archive_path }}'
    sha256sum: '{{ download.jetty.sha256sum }}'

- name: 'Extract jetty distribution'
  shell: >
    umask 0027;
    tar zx -C {{ jetty.root }} -f {{ jetty_dist_archive_path }} --no-same-permissions;
    chgrp -R jetty {{ jetty.home }}
    creates={{ jetty.home }}

- name: 'Remove demo-base'
  file:
    path: '{{ jetty.home }}/demo-base'
    state: absent

- name: 'Symlink jetty to installed distribution'
  file:
    name: '{{ jetty.current }}'
    src: '{{ jetty.home }}'
    owner: root
    group: jetty
    state: link
    force: yes

- name: 'Create directories required for JETTY_BASE'
  file:
    name: '{{ item }}'
    state: directory
    owner: root
    group: jetty
    mode: 0750
  with_items:
    - '{{ jetty.base }}'
    - '{{ jetty.base }}/etc'
    - '{{ jetty.base }}/lib'
    - '{{ jetty.base }}/lib/ext'
    - '{{ jetty.base }}/lib/logback'
    - '{{ jetty.base }}/lib/slf4j'
    - '{{ jetty.base }}/modules'
    - '{{ jetty.base }}/resources'
    - '{{ jetty.base }}/start.d'
    - '{{ jetty.base }}/webapps'

# Files in jetty.base/etc

- name: 'Create Logback access configuration'
  template:
    dest: '{{ jetty.base }}/etc/jetty-logback-access.xml'
    src: 'templates/jetty/jetty-logback-access.xml'
    owner: root
    group: jetty
    mode: 0640
    backup: yes

- name: 'Create SSL Tweak configuration'
  template:
    dest: '{{ jetty.base }}/etc/tweak-ssl.xml'
    src: 'templates/jetty/tweak-ssl.xml'
    owner: root
    group: jetty
    mode: 0640
    backup: yes

# Files in jetty.base/modules

- name: 'Set http.mod'
  template:
    dest: '{{ jetty.base }}/modules/http.mod'
    src: 'templates/jetty/http.mod'
    owner: root
    group: jetty
    mode: 0640
    backup: yes

- name: 'Set idp.mod'
  template:
    dest: '{{ jetty.base }}/modules/idp.mod'
    src: 'templates/jetty/idp.mod'
    owner: root
    group: jetty
    mode: 0640
    backup: yes

# Files in jetty.base/resources

- name: 'Set logback-access configuration'
  template:
    dest: '{{ jetty.base }}/resources/logback-access.xml'
    src: 'templates/jetty/logback-access.xml'
    owner: root
    group: jetty
    mode: 0640
    backup: yes

- name: 'Set logback configuration'
  template:
    dest: '{{ jetty.base }}/resources/logback.xml'
    src: 'templates/jetty/logback.xml'
    owner: root
    group: jetty
    mode: 0640
    backup: yes

# Files in jetty.base/start.d

- name: 'Set idp.ini configuration'
  template:
    dest: '{{ jetty.base }}/start.d/idp.ini'
    src: 'templates/jetty/idp.ini'
    owner: root
    group: jetty
    mode: 0640
    backup: yes

# Files in jetty.base/webapps

- name: 'Set idp.xml'
  template:
    dest: '{{ jetty.base }}/webapps/idp.xml'
    src: 'templates/jetty/idp.xml'
    owner: root
    group: jetty
    mode: 0640
    backup: yes

- name: 'Set static.xml'
  template:
    dest: '{{ jetty.base }}/webapps/static.xml'
    src: 'templates/jetty/static.xml'
    owner: root
    group: jetty
    mode: 0640
    backup: yes

# Files in jetty.base

- name: 'Set start.ini'
  template:
    dest: '{{ jetty.base }}/start.ini'
    src: 'templates/jetty/start.ini'
    owner: root
    group: jetty
    mode: 0640
    backup: yes

# Jetty defaule in /etc/default

- name: 'Set /etc/default/jetty'
  template:
    dest: '/etc/default/jetty'
    src: 'templates/jetty/jetty'
    owner: root
    group: jetty
    mode: 0644
    backup: yes

- name: 'Set permissions on jetty directory'
  file:
    path: '{{ jetty.home }}'
    owner: root
    group: jetty
    mode: 0750
    state: directory

- name: 'Create jetty state directory'
  file:
    path: '{{ jetty.state_directory }}'
    owner: jetty
    group: jetty
    state: directory
    mode: 0700

- name: 'Create a tmp directory for jetty'
  file:
    path: '{{ jetty.tmp_directory }}'
    owner: jetty
    group: jetty
    state: directory
    mode: 0700

- name: 'Set permissions on jetty directory'
  file:
    path: '{{ item }}'
    owner: root
    group: jetty
    mode: 0750
  with_items:
  - '{{ jetty.home }}'
  - '{{ jetty.home }}/modules'
  - '{{ jetty.home }}/resources'
  - '{{ jetty.home }}/etc'
  - '{{ jetty.home }}/lib'
  - '{{ jetty.home }}/webapps'
  - '{{ jetty.home }}/bin'

- name: 'Set executable files for jetty'
  file:
    path: '{{ item }}'
    owner: root
    group: jetty
    mode: 0750
  with_items:
  - '{{ jetty.home }}/bin/jetty.sh'
